version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  built:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"

  testing:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"
      - run: python -m pip install -r requirements.txt
      - run: pytest -vvv --cov code
      - codecov/upload

workflows:
  first_build:
    jobs:
      - built
      - testing:
          requires:
          - built

